language: python
python:
  - "3.4"
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  python manage.py test
deploy:
  provider: heroku
  api_key: 96a23a17-2f61-4b6d-8840-29805d4167b6
  app: ilja-try-test